CREATE SCHEMA IF NOT EXISTS petclinic;

CREATE TABLE IF NOT EXISTS types (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);
CREATE INDEX ON types (name);

CREATE TABLE IF NOT EXISTS owners (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT,
  last_name  TEXT,
  address    TEXT,
  city       TEXT,
  telephone  TEXT
);
CREATE INDEX ON owners (last_name);

CREATE TABLE IF NOT EXISTS pets (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT,
  birth_date DATE,
  type_id    INT NOT NULL REFERENCES types (id),
  owner_id   INT REFERENCES owners (id)
);
CREATE INDEX ON pets (name);
CREATE INDEX ON pets (owner_id);

CREATE TABLE IF NOT EXISTS vet
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      VARCHAR(255),
    last_name       VARCHAR(255),
    email           VARCHAR(255),
    hourly_rate     INT
);

CREATE TABLE IF NOT EXISTS speciality
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS vet_specialities
(
    vet_id              INT REFERENCES vet (id) NOT NULL,
    specialities_id     INT REFERENCES speciality (id) NOT NULL,
    UNIQUE (vet_id, specialities_id)
);

CREATE TABLE IF NOT EXISTS visits (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id      INT REFERENCES pets (id),
  vet_id      INT REFERENCES vet (id),
  visit_date  DATE,
  description TEXT
);
CREATE INDEX ON visits (pet_id);

ALTER TABLE owners ALTER COLUMN address TYPE VARCHAR(255) USING (address::VARCHAR(255));

ALTER TABLE owners ALTER COLUMN city TYPE VARCHAR(255) USING (city::VARCHAR(255));

ALTER TABLE visits ALTER COLUMN description TYPE VARCHAR(255) USING (description::VARCHAR(255));

ALTER TABLE owners ALTER COLUMN first_name TYPE VARCHAR(255) USING (first_name::VARCHAR(255));

ALTER TABLE owners ALTER COLUMN last_name TYPE VARCHAR(255) USING (last_name::VARCHAR(255));

ALTER TABLE pets ALTER COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE types ALTER COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE owners ALTER COLUMN telephone TYPE VARCHAR(255) USING (telephone::VARCHAR(255));